name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 确保检出所有历史

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython  # 安装 buildozer 和 cython

    - name: S1et up environment variables
      run: |       
        
        
    - name: S2et up environment variables
      run: |       
        sudo apt-get update
        
    - name: S3et up environment variables
      run: |       
        sudo apt-get install -y aidl
        
    - name: S4et up environment variables
      run: |       
        mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
        mkdir -p ~/home/runner/.buildozer/android/platform/android-sdk/tools/bin
    - name: S5et up environment variables
      run: |       
       
        cp /usr/bin/aidl ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
       
    - name: S6et up environment variables
      run: |       
        cp /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager ~/home/runner/.buildozer/android/platform/android-sdk/tools/bin/
       
    - name: S7et up environment variables
      run: |       
        chmod 777 ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/aidl
       
    - name: S8et up environment variables
      run: |       
        chmod 777 ~/home/runner/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
           
    - name: S9et up environment variables
      run: |       
        
     find / -name sdkmanager




    - name: Build Android app
      run: |
        export PATH="$PATH:/home/runner/.buildozer/android/platform/android-sdk/tools/bin"

        buildozer android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: ./bin/*.apk
