# 名称: Android CI
name: Android CI

# 触发器: 当有代码被推送到仓库时，此工作流将被触发
on: [push]

# 工作流中的作业列表
jobs:
  # 作业的名称
  build:
    # 指定运行作业的虚拟机环境
    runs-on: ubuntu-latest

    # 作业中的步骤列表
    steps:
      # 使用 'actions/checkout' Action 检出仓库代码
      - uses: actions/checkout@v2

      # 名称: 设置 Python 环境
      - name: Set up Python
        # 使用 'actions/setup-python' Action 配置 Python 环境
        uses: actions/setup-python@v2
        # 指定要安装的 Python 版本
        with:
          python-version: '3.8'
          

      # 名称: 接受 Android SDK 许可协议
      - name: Accept Android
        # 运行以下命令行脚本
        run: |
          sudo apt-get update
          
          
          sudo apt-get install aidl
          export PATH=$PATH:/usr/local/lib/android/sdk/cmdline-tools/latest/bin

          # 创建整个目录结构
          mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/

          which aidl
          cp /usr/bin/aidl ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
          chmod 777 ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/aidl
          pip3 install cython

          pip3 install kivy
          pip3 install buildozer
          buildozer -v android debug
