name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 使用Python 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
    - name: Build Android app
      run: |
        # 确保在仓库根目录下
        buildozer android debug
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: ./bin/*.apk
