name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up Android SDK tools
        run: |
          which sdkmanager
          sudo apt-get update
          sudo apt-get install -y aidl
          mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
          cp /usr/bin/aidl ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
          cp /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
          chmod 777 ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/aidl
          chmod 777 ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/sdkmanager
          pip3 install cython
          pip3 install kivy
          pip3 install buildozer
          buildozer -v android debug
