name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 确保检出所有历史

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython  # 安装 buildozer 和 cython

    - name: Set up Android SDK
      run: |
        sdkmanager --update
        sdkmanager "platform-tools" "build-tools;29.0.3"  # 安装平台工具和构建工具

    - name: Add Android SDK to PATH
      run: |
        echo "$ANDROID_HOME/platform-tools" >>$GITHUB_PATH
        echo "$ANDROID_HOME/build-tools/29.0.3" >>$GITHUB_PATH
      env:
        ANDROID_HOME: ${{ github.workspace }}/android-sdk-linux

    - name: Check for buildozer.spec
      run: |
        ls -la  # 列出所有文件以确认 buildozer.spec 的存在

    - name: Build Android app
      run: |
        buildozer android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: ./bin/*.apk
