name: paper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-Android:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find all built APK files
        id: find-apk
        run: |
          apk_paths=$(find app/build/outputs/apk/ -name "*.apk")
          echo "Found APK paths: $apk_paths"
          echo "apk_paths=$apk_paths" >> $GITHUB_ENV

      - name: Upload all build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app-artifacts
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk