name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 确保检出所有历史

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython  # 安装 buildozer 和 cython

    - name: Set up environment variables
      run: |       
        which sdkmanager
        sudo apt-get update
        sudo apt-get install -y aidl
        mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
        cp /usr/bin/aidl ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
        cp /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/
        chmod 777 ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/aidl
        chmod 777 ~/.buildozer/android/platform/android-sdk/build-tools/35.0.0/sdkmanager



    - name: Build Android app
      run: |
        buildozer android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: ./bin/*.apk
