name: Build and Test CI
# 定义工作流程的名称

on: [push]

# 定义触发工作流程的事件。这里配置为在向main分支进行push操作时触发。

jobs:
  build-Android:
    runs-on: ubuntu-latest
    # 定义作业的名称（build）和运行作业的虚拟机环境（最新版本的Ubuntu）
    permissions:
      contents: read
      packages: write
    
    # 设置作业的权限，contents权限为读取仓库内容，packages权限为写入包管理器。

    steps:
    - uses: actions/checkout@v2
      # 使用actions/checkout@v3操作来检出仓库，这样可以在后续步骤中访问仓库的代码。


    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: gradle
      # 使用actions/setup-java@v3操作来设置Java开发环境，指定Java版本为18，使用Adoptium作为JDK的发行版，并启用Gradle缓存。
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      # 运行shell命令来执行Gradle构建脚本，该脚本位于项目根目录下的gradlew文件，并执行构建任务。
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk