name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 确保检出所有历史

    # 设置环境变量
    - name: Set up environment variables
      run: |
        echo "ANDROID_SDK_ROOT=${{ github.workspace }}/android-sdk" >>$GITHUB_ENV
        echo "ANDROID_HOME=${{ github.workspace }}/android-sdk" >>$GITHUB_ENV
        echo "JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64" >> $GITHUB_ENV

    # 接受所有 SDK 许可证
    - name: Accept all SDK licenses
      run: |
        echo "Accepting SDK licenses..."
        yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses || true
        echo "SDK licenses accepted."

    # 安装 Android SDK Build-Tools 35
    - name: Set up Android SDK Build-Tools 35
      run: |
        echo "Installing Build-Tools 35..."
        sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "build-tools;35.0.0"
        echo "Build-Tools 35 installed."

    # 安装其他必要的 SDK 包
    - name: Install other necessary SDK packages
      run: |
        echo "Installing other necessary SDK packages..."
        sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-31"
        echo "Other necessary SDK packages installed."

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    # 安装 Python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # 安装依赖
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        pip install buildozer cython

    # 构建Android应用
    - name: Build Android app
      run: |
        echo "Building Android app..."
        # 直接构建Android应用，不需要初始化
        buildozer android debug

    # 上传生成的APK文件
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: ./bin/*.apk
