name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 确保检出所有历史

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython  # 安装 buildozer 和 cython

    - name: Set up environment variables
      run: |
        ANDROID_SDK_ROOT=$HOME/android-sdk
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >>$GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >>$GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/platform-tools" >>$GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >>$GITHUB_PATH

    - name: Set up Android SDK
      run: |
        # 下载 Android SDK
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -q || { echo "Failed to download SDK tools"; exit 1; }
        unzip -q sdk-tools-linux-4333796.zip -d $ANDROID_SDK_ROOT || { echo "Failed to unzip SDK tools"; exit 1; }
        # 使用 yes 命令自动同意许可证
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || { echo "Failed to accept SDK licenses"; exit 1; }
        # 安装 SDK 组件
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;29.0.3" "build-tools;35.0.0" > /dev/null || { echo "Failed to install SDK components"; exit 1; }

    - name: Check for buildozer.spec
      run: |
        if [ ! -f "buildozer.spec" ]; then
          echo "buildozer.spec not found"
          exit 1
        fi

    - name: Build Android app
      run: |
        buildozer android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: ./bin/*.apk
