name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 确保检出所有历史

    # 设置环境变量
    - name: Set up environment variables
      run: |
        echo "ANDROID_SDK_ROOT=${{ github.workspace }}/android-sdk" >>$GITHUB_ENV
        echo "ANDROID_HOME=${{ github.workspace }}/android-sdk" >>$GITHUB_ENV
        # 设置正确的 JAVA_HOME 路径
        echo "JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64" >> $GITHUB_ENV

    # 安装 Android SDK Platform-Tools 3.5
    - name: Set up Android SDK Platform-Tools 3.5
      run: |
        sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools;3.5" || true
        echo "${ANDROID_SDK_ROOT}/platform-tools" >>$GITHUB_PATH

    # 安装 Python 3.8
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython  # 安装 buildozer 和 cython

    # 构建Android应用
    - name: Build Android app
      run: |
        # 直接构建Android应用，不需要初始化
        buildozer android debug

    # 上传生成的APK文件
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: ./bin/*.apk
