name: Delete All Artifacts

on:
  workflow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # 允许删除工件
      contents: read  # 允许读取仓库内容
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete all artifacts
        run: |
          gh api repos/${{ github.repository }}/actions/artifacts --paginate | jq -r '.artifacts[].id' | xargs -I{} gh api repos/${{ github.repository }}/actions/artifacts/{} -X DELETE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}