name: Build Android App and EXE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Ubuntu的最新版作为运行环境

    steps:
      - uses: actions/checkout@v2

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 安装PyInstaller来构建.exe文件
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 构建可执行文件
      - name: Build EXE
        run: |
          pyinstaller --onefile hello.py
        # 确保hello.py脚本在正确的路径下

      # 上传.exe文件
      - name: Upload EXE
        uses: actions/upload-artifact@v2
        with:
          name: python-exe
          path: dist/*.exe

      # 安装Android SDK和NDK
      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v0.2
        with:
          sdk-version: '29'
          ndk-version: '21.3.6528147'

      # 安装Kivy和Buildozer
      - name: Install Kivy and Buildozer
        run: |
          pip install kivy buildozer

      # 初始化Buildozer环境并构建Android应用
      - name: Build Android App
        run: |
          buildozer init
          # 更新spec文件以适应您的应用需求
          echo "requirements = kivy" >> ./buildozer.spec
          echo "title = HelloApp" >> ./buildozer.spec
          echo "package.name = hello" >> ./buildozer.spec
          echo "package.domain = org.test" >> ./buildozer.spec
          # 构建Android应用
          buildozer android debug
        working-directory: ./  # 假设您在仓库的根目录下

      # 上传APK
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: ./bin/*.apk
