name: Build Android App and EXE

on: [push]

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 安装PyInstaller来构建.exe文件
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 构建可执行文件
      - name: Build EXE
        run: |
          pyinstaller --onefile hello.py
        # 确保hello.py脚本在正确的路径下

      # 上传.exe文件
      - name: Upload EXE
        uses: actions/upload-artifact@v2
        with:
          name: python-exe
          path: dist/*.exe

  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 安装Android SDK和NDK
      - name: Set up Android SDK and NDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Android SDK and NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          mkdir -p ~/android/
          cd ~/android/
          curl -O https://dl.google.com/android/repository/platform-tools_latest.zip
          unzip platform-tools_latest.zip -d ~/android/
          curl -O https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          unzip android-ndk-r21b-linux-x86_64.zip -d ~/android/
          echo 'export ANDROID_HOME=~/android/' >> ~/.bashrc
          echo 'export PATH=$PATH:~/android/' >> ~/.bashrc
          source ~/.bashrc
          echo 'Installation complete'

      # 安装Kivy和Buildozer
      - name: Install Kivy and Buildozer
        run: |
          pip install kivy buildozer

      # 初始化Buildozer环境并构建Android应用
      - name: Build Android App
        run: |
          buildozer init
          # 更新spec文件以适应您的应用需求
          echo "requirements = kivy" >> ./buildozer.spec
          echo "title = HelloApp" >> ./buildozer.spec
          echo "package.name = hello" >> ./buildozer.spec
          echo "package.domain = org.test" >> ./buildozer.spec
          # 构建Android应用
          buildozer android debug
        working-directory: ./  # 假设您在仓库的根目录下

      # 上传APK
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: ./bin/*.apk
