name: Build Android App and EXE

on: [p1ush]

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 安装PyInstaller来构建.exe文件
      - name: Install PyInstaller
        run: pip install pyinstaller
        pip install python-docx
        pip install sparkdesk-api==1.6.0

      # 构建可执行文件
      - name: Build EXE
        run: |
          pyinstaller --onefile hello.py
        # 确保hello.py脚本在正确的路径下

      # 上传.exe文件
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: python-exe
          path: dist/*.exe
